spring:
  config:
    activate:
      on-profile:
        - dev

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  show-actuator: true

server:
  port: 8088

rest-for-kafka:
  schema.registry.url: http://localhost:8888/
  schema.registry.subjects.value-suffix": TRUE
  kafka:
    bootstrap-servers: ${REST_FOR_KAFKA_BOOTSTRAP_SERVERS:localhost\:9092}
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      client-id: test-client-id
