spring:
  config:
    activate:
      on-profile:
        - dev
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: ${CLIENT_ID}
#            client-secret: ${CLIENT_SECRET}
            #redirect-uri: "http://localhost:8088/swagger-ui/index.html"

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html


server:
  port: 8088

rest-for-kafka:
  schema.registry.url: http://localhost:8081/
  schema.registry.subjects.value-suffix": TRUE
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      client-id: test-client-id
